# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-01 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('investor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('ssn', models.CharField(max_length=12, null=True, unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('trade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Investors')),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=500)),
                ('stock_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stocks'),
        ),
    ]
