# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='num',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
