# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_portfolio_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='trade_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
