stu={'Adele': {'All I Ask': {'lesson', 'sure', 'word', 'speak', 'night', 'cause', 'leave', 'friend', 'need', 'play', 'run', 'vicious', 'give', 'eyes', 'wanna', 'hold', 'tell', 'left', 'last', 'next', 'said', 'lovers', 'one', 'knows', 'ends', 'take', 'honesty', 'use', 'look', 'love', 'since', 'pretend', 'memory', 'forgiveness', 'matters', 'get', 'door', 'remember', 'asking', 'wrong', 'coming', 'say', 'scared', 'let', 'cruel', 'tomorrow', 'way', 'hand', 'like', 'heart', 'ask', 'know'}, "Can't Let Go": {'platter', 'cold', 'hard', 'hid', 'lump', 'thought', 'truth', 'faked', 'much', 'thrill', 'feel', 'note', 'life', 'tell', 'gave', 'sometimes', 'like', 'coat', 'said', 'dark', 'heaven', 'told', 'throat', 'yet', 'slow', 'die', 'lied', 'wanted', 'go', 'save', 'love', 'thinking', 'oooh', 'went', 'baby', 'kill', 'seam', 'loved', 'wrong', 'round', 'arms', 'write', 'let', 'find', 'hope', 'even', 'everything', 'wrote', 'time', 'know'}}, 'Bob Dylan': {'4Th Time Around': {'forget', 'back', 'hummed', 'give', 'waited', 'screamed', 'till', 'filled', 'drawer', 'piece', 'tried', 'got', 'threw', 'hallway', 'make', 'went', 'loved', 'boot', 'shirt', 'floor', 'face', 'something', 'thumbs', 'clear', 'thought', 'drum', 'tapped', 'jamaican', 'spit', 'last', 'cried', 'sense', 'deaf', 'better', 'dirt', 'stood', 'get', 'crutch', 'knocked', 'walked', 'finding', 'words', 'suit', 'leaned', 'handed', 'asked', 'much', 'covered', 'forced', 'come', 'wheelchair', 'said', 'picture', 'mine', 'gum', 'must', 'felt', 'straightened', 'time', 'ask', 'hands', 'breaking', 'buttoned', 'leave', 'fell', 'waste', 'eyes', 'worked', 'outside', 'rum', 'everybody', 'look', 'go', 'else', 'forgotten', 'wasted', 'red', 'gallantly', 'pockets', 'brought', 'took', 'shoe'}, 'A Satisfied Mind': {'lost', 'heard', 'little', 'happened', 'richer', 'ones', 'certain', 'world', 'game', 'ten', 'things', 'mind', 'leave', 'run', 'life', 'know', 'doubt', 'wading', 'dreamed', 'suddenly', 'hmm', 'lifes', 'times', 'old', 'satisfied', 'one', 'many', 'money', 'man', 'far', 'fortune', 'comes', 'friends', 'get', 'loved', 'someone', 'say', 'find', 'way', 'everything', 'fame', 'start', 'time', 'dime', 'hard'}}}

newstu={'Adele': {'All I Ask': {'cause', 'pretend', 'heart', 'speak', 'lovers', 'friend', 'tell', 'ends', 'remember', 'coming', 'wrong', 'take', 'since', 'cruel', 'left', 'knows', 'word', 'said', 'give', 'say', 'last', 'know', 'hand', 'leave', 'scared', 'eyes', 'night', 'one', 'run', 'play', 'use', 'look', 'tomorrow', 'get', 'let', 'memory', 'next', 'honesty', 'matters', 'way', 'forgiveness', 'like', 'need', 'chorus', 'door', 'sure', 'lesson', 'bridge', 'asking', 'pre-chorus', 'love', 'wanna', 'hold', 'ask', 'verse', 'vicious'}, "Can't Let Go": {'much', 'note', 'die', 'lump', 'tell', 'time', 'truth', 'wrong', 'thrill', 'wrote', 'loved', 'kill', 'went', 'sometimes', 'coat', 'heaven', 'even', 'yet', 'lied', 'slow', 'said', 'feel', 'know', 'baby', 'thought', 'platter', 'wanted', 'throat', 'dark', 'oooh', 'life', 'cold', 'round', 'let', 'faked', 'hid', 'like', 'go', 'chorus', 'hard', 'outro', 'hope', 'everything', 'bridge', 'pre-chorus', 'love', 'gave', 'find', 'save', 'seam', 'write', 'told', 'thinking', 'arms', 'verse'}}, 'Bob Dylan': {'4Th Time Around': {'boot', 'red', 'deaf', 'much', 'hallway', 'wasted', 'handed', 'wheelchair', 'pockets', 'screamed', 'tried', 'asked', 'time', 'tapped', 'crutch', 'spit', 'clear', 'sense', 'loved', 'went', 'floor', 'ask', 'else', 'felt', 'forgotten', 'filled', 'thumbs', 'straightened', 'gallantly', 'hands', 'said', 'face', 'worked', 'give', 'gum', 'waited', 'last', 'till', 'shirt', 'make', 'threw', 'everybody', 'jamaican', 'drum', 'thought', 'eyes', 'leave', 'piece', 'dirt', 'leaned', 'better', 'finding', 'drawer', 'took', 'look', 'something', 'mine', 'come', 'get', 'got', 'shoe', 'stood', 'back', 'waste', 'go', 'fell', 'picture', 'walked', 'forget', 'hummed', 'outside', 'must', 'rum', 'words', 'knocked', 'breaking', 'cried', 'forced', 'covered', 'buttoned', 'suit', 'brought'}, 'A Satisfied Mind': {'dreamed', 'lifes', 'things', 'suddenly', 'times', 'time', 'richer', 'satisfied', 'lost', 'fame', 'loved', 'little', 'dime', 'ones', 'wading', 'man', 'say', 'know', 'ten', 'friends', 'leave', 'one', 'heard', 'run', 'life', 'start', 'comes', 'fortune', 'way', 'get', 'happened', 'old', 'hard', 'mind', 'far', 'everything', 'money', 'many', 'hmm', 'world', 'find', 'certain', 'game', 'someone', 'doubt'}}}
b={'Adele': {'All I Ask': {'lesson', 'sure', 'word', 'speak', 'night', 'need', 'friend', 'leave', 'bridge', 'play', 'run', 'vicious', 'give', 'chorus', 'cause', 'eyes', 'wanna', 'hold', 'tell', 'left', 'last', 'one', 'lovers', 'said', 'next', 'verse', 'knows', 'ends', 'take', 'honesty', 'use', 'look', 'since', 'love', 'pretend', 'memory', 'forgiveness', 'matters', 'get', 'door', 'remember', 'asking', 'wrong', 'coming', 'say', 'scared', 'let', 'cruel', 'tomorrow', 'way', 'hand', 'like', 'heart', 'ask', 'know'}, "Can't Let Go": {'platter', 'cold', 'hid', 'thought', 'lump', 'truth', 'much', 'faked', 'time', 'thrill', 'feel', 'bridge', 'note', 'chorus', 'life', 'know', 'tell', 'gave', 'sometimes', 'coat', 'said', 'dark', 'told', 'heaven', 'verse', 'throat', 'slow', 'die', 'lied', 'wanted', 'go', 'wrote', 'save', 'love', 'thinking', 'oooh', 'went', 'baby', 'kill', 'seam', 'loved', 'outro', 'wrong', 'arms', 'round', 'write', 'let', 'find', 'hope', 'even', 'everything', 'like', 'yet', 'hard'}}, 'Bob Dylan': {'4Th Time Around': {'forget', 'back', 'hummed', 'give', 'waited', 'screamed', 'till', 'left', 'lies', 'filled', 'drawer', 'piece', 'tried', 'threw', 'make', 'hallway', 'got', 'went', 'loved', 'boot', 'shirt', 'floor', 'face', 'something', 'thumbs', 'clear', 'thought', 'drum', 'tapped', 'jamaican', 'spit', 'last', 'sense', 'cried', 'deaf', 'better', 'dirt', 'stood', 'shoe', 'get', 'crutch', 'knocked', 'walked', 'finding', 'words', 'suit', 'leaned', 'handed', 'asked', 'much', 'cute', 'covered', 'forced', 'wheelchair', 'said', 'picture', 'mine', 'gum', 'must', 'felt', 'straightened', 'time', 'ask', 'hands', 'dear', 'breaking', 'buttoned', 'leave', 'fell', 'waste', 'eyes', 'worked', 'outside', 'rum', 'everybody', 'look', 'go', 'else', 'forgotten', 'wasted', 'red', 'gallantly', 'pockets', 'brought', 'took', 'come'}, 'A Satisfied Mind': {'lost', 'heard', 'little', 'ones', 'richer', 'happened', 'certain', 'world', 'game', 'ten', 'things', 'mind', 'leave', 'run', 'life', 'know', 'doubt', 'wading', 'dreamed', 'suddenly', 'hmm', 'lifes', 'times', 'old', 'satisfied', 'one', 'many', 'man', 'money', 'far', 'fortune', 'comes', 'friends', 'get', 'loved', 'someone', 'say', 'find', 'way', 'everything', 'fame', 'start', 'time', 'dime', 'hard'}}}

for x in stu :
    for y in stu[x]:
        print(stu[x][y].symmetric_difference(b[x][y]))

print("*"*80)

for x in newstu :
    for y in newstu[x]:
        print(newstu[x][y].symmetric_difference(b[x][y]))