USE FinTech_Training;

DROP TABLE IF EXISTS PORTFOLIO;
DROP TABLE IF EXISTS INVESTORS;
DROP TABLE IF EXISTS STOCKS;

CREATE TABLE INVESTORS (
	INVESTOR_ID NUMERIC NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    SSN VARCHAR(12) NOT NULL,
    ADDRESS VARCHAR(500) NULL,
    PRIMARY KEY (INVESTOR_ID),
    UNIQUE KEY (SSN)
);

CREATE TABLE STOCKS (
    TICKER VARCHAR(10) NOT NULL,
    COMPANY VARCHAR(500) NOT NULL,
    STOCK_CLASS VARCHAR(100) NULL,
    PRIMARY KEY(TICKER)
);

CREATE TABLE PORTFOLIO (
	TRADE_ID NUMERIC NOT NULL,
    INVESTOR_ID NUMERIC NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
	PRICE  NUMERIC NOT NULL,
    PRIMARY KEY (TRADE_ID),
    FOREIGN KEY (INVESTOR_ID) REFERENCES INVESTORS(INVESTOR_ID),
    FOREIGN KEY (TICKER) REFERENCES STOCKS(TICKER)
);